SELECT
    wos_id,
    issn,
    doi,
    title,
    pubtype,
    doctype,
    volume,
    issue,
    pubyear,
    pubmonth,
    pubday,
    source,
    abstract
FROM
    union_publications
WHERE
    source IN ('ANTIPODE', 
                'AREA',
                'CASE STUDIES IN THE ENVIRONMENT',
                'CHILDREN, YOUTH, AND ENVIRONMENTS',
                'CONSERVATION AND SOCIETY',
                'CULTURAL GEOGRAPHIES',
                'DISASTERS',
                'ECOLOGICAL ECONOMICS',
                'ECOLOGY AND SOCIETY',
                'ENERGY & ENVIRONMENT',
                'ENERGY POLICY',
                'ENERGY RESEARCH & SOCIAL SCIENCE',
                'ENVIRONMENT AND BEHAVIOR',
                'ENVIRONMENT AND PLANNING',
                'ENVIRONMENT AND URBANIZATION',
                'ENVIRONMENTAL AND RESOURCE ECONOMICS',
                'ENVIRONMENTAL HEALTH PERSPECTIVES',
                'ENVIRONMENTAL RESEARCH LETTERS',
                'ENVIRONMENTAL SCIENCE & TECHNOLOGY',
                'ENVIRONMENTAL SOCIOLOGY',
                'ENVIRONMENTAL VALUES',
                'GEOFORUM',
                'GLOBAL ENVIRONMENTAL CHANGE',
                'GLOBAL ENVIRONMENTAL POLITICS',
                'HASTINGS WEST-NORTHWEST JOURNAL OF ENVIRONMENTAL LAW AND POLICY',
                'HUMAN ECOLOGY',
                'INDOOR AND BUILD ENVIRONMENT',
                'INTERNATIONAL JOURNAL OF ECOLOGY & DEVELOPMENT',
                'INTERNATIONAL REGIONAL SCIENCE REVIEW',
                'THE JOURNAL OF ENVIRONMENT & DEVELOPMENT',
                'JOURNAL OF ENVIRONMENTAL ASSESSMENT POLICY AND MANAGEMENT',
                'JOURNAL OF ENVIRONMENTAL ECONOMICS AND MANAGEMENT',
                'JOURNAL OF ENVIRONMENTAL STUDIES AND SCIENCES',
                'JOUNRAL OF ENVIRONMENTAL PSYCHOLOGY',
                'JOURNAL OF POLITICAL ECOLOGY',
                'LAND ECONOMICS',
                'NATURAL RESOURCES FORUM',
                'NATURE AND CULTURE',
                'ORGANIZATION & ENVIRONMENT',
                'PAPERS IN REGIONAL SCIENCE',
                'POPULATION AND ENVIRONMENT',
                'PROGRESS IN HUMAN GEOGRAPHY',
                'REVIEW OF ENVIRONMENTAL ECONOMICS AND POLICY',
                'SOCIETY & NATURAL RESOURCES',
                'WATER RESOURCES RESEARCH');